[project]
name = "dragon-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jujumilk3", email = "jujumilk3@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "matplotlib>=3.11.2",
]

[project.scripts]
dragon-bench = "dragon_bench:main"

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"
